package com.example.demo10.dto;

import java.util.ArrayList;
import java.util.List;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Music {
	
	private String singer;
	private String title;
	private String imageUrl;
	private String lyris;
	
	// 샘플 데이터
	public static List<Music> sampleMusic() {
		ArrayList<Music> list = new ArrayList<>();
		
		list.add(new Music("임영웅","A bientot", "https://cdnimg.melon.co.kr/cm2/album/images/109/23/444/10923444_20220502140600_500.jpg/melon/resize/120/quality/80/optimize", "A bientot\r\n"
				+ "A bientot\r\n"
				+ "이 밤이 지나면 괜찮아질 수 있을까\r\n"
				+ "쓰린 내 맘이 회복될 수가 있을까\r\n"
				+ "네가 떠난 빈자리가 너무 크니까\r\n"
				+ "그 공허함에 깔려 겨우 살고 있잖아\r\n"
				+ "기억은 잔인하고 후유증은 지독해\r\n"
				+ "겨우 잠을 이뤄도 꿈자리는 뒤숭숭해\r\n"
				+ "마음의 반을 도려내 버리고 난 후에\r\n"
				+ "너라는 감옥에서 풀려날 수 있었네\r\n"
				+ "38도 탕 안처럼 포근한\r\n"
				+ "그날의 온도는 아직도 나의 가슴에\r\n"
				+ "깊게 뿌리내려 뻗어 미련이란 놈은\r\n"
				+ "공기처럼 내 마음을 드나드네\r\n"
				+ "넌 빌런이자 하나님이야\r\n"
				+ "셀 수 없는 많은 노래를\r\n"
				+ "잉태하고 부숴버렸네\r\n"
				+ "널 향해 나는 기도해\r\n"
				+ "널 향해 나는 기도해\r\n"
				+ "A bientot\r\n"
				+ "A bientot\r\n"
				+ "인생은 너무 외로워\r\n"
				+ "너에게 전화를 거네요\r\n"
				+ "A bientot\r\n"
				+ "A bientot\r\n"
				+ "인생은 너무 외로워\r\n"
				+ "너에게 전화를 거네요"));
		
		list.add(new Music("임영웅","사랑해 진짜", "https://cdnimg.melon.co.kr/cm2/album/images/109/23/444/10923444_20220502140600_500.jpg/melon/resize/120/quality/80/optimize", "숱한 날들 모두 내게 남아있는 추억들\r\n"
				+ "빛바랜 기억들 사이\r\n"
				+ "그대 모습만이 아련하게 빛나네\r\n"
				+ "지나간 세월이 야속하진 않아\r\n"
				+ "그댈 만났으므로\r\n"
				+ "피어날 내일을 기대해 오\r\n"
				+ "그대 내게 와줬으니\r\n"
				+ "나 진짜 진짜 당신만을 사랑하고 사랑해\r\n"
				+ "내 삶의 반쪽 그대만을\r\n"
				+ "아 나는 그대만 보고 있어\r\n"
				+ "아 나는 그대를 사랑합니다\r\n"
				+ "오색빛의 색이 물든 미완성의 그림 하나\r\n"
				+ "그래 내 마음 같겠지\r\n"
				+ "어느 날 그대가 내게 오기 전까지\r\n"
				+ "지나간 시간이 야속하진 않아\r\n"
				+ "그댈 만났으므로\r\n"
				+ "피어날 내일을 기대해\r\n"
				+ "그대 내게 와줬으니\r\n"
				+ "나 진짜 진짜 당신만을 사랑하고 사랑해\r\n"
				+ "내 삶의 반쪽 그대만을\r\n"
				+ "아 나는 그대만 보고 있어\r\n"
				+ "아 나는 그대를 사랑합니다"));
		
		list.add(new Music("(여자)아이들","MY BAG", "https://cdnimg.melon.co.kr/cm2/album/images/108/90/384/10890384_20220314111504_500.jpg/melon/resize/120/quality/80/optimize", "Red five diamonds in my bag\r\n"
				+ "If you wanna see it, dance to a beat like that\r\n"
				+ "My mama saw it and ‘Oh my god dang’\r\n"
				+ "Ok I’ll show you what’s in my bag\r\n"
				+ "\r\n"
				+ "Red five diamonds in my bag\r\n"
				+ "If you wanna see it, dance to a beat like that\r\n"
				+ "My mama saw it and ‘Oh my god dang’\r\n"
				+ "Ok I’ll show you what’s in my bag\r\n"
				+ "\r\n"
				+ "Uh oh I know you like it\r\n"
				+ "My voice는 말해 뭐 해 God dang\r\n"
				+ "Uh oh I just like it\r\n"
				+ "태생부터 많은 Money 관심 없지\r\n"
				+ "\r\n"
				+ "싸가지 없는 무대의 못된 범인의 눈빛\r\n"
				+ "Fantasy란 말은 나를 빼고 다 금지\r\n"
				+ "글러 먹은 너의 감 모두 나를 위한 밥\r\n"
				+ "독한 Vibe sugar high 맛 좀 봐라 모두 Die\r\n"
				+ "\r\n"
				+ "Rum-rum-rum Rumble 다 Crumble\r\n"
				+ "이 Voice는 Drum에도 No lose\r\n"
				+ "No no no lovely I’m Bumblebee\r\n"
				+ "그냥 훅 들어갈 뿐 안 해 One, two\r\n"
				+ "\r\n"
				+ "I never had 겁 a.k.a “Giant dog”\r\n"
				+ "아차 하고 쓰다듬은 다쳐 이건 어쩜 범\r\n"
				+ "I value my love 그만 두들겨 너\r\n"
				+ "머리 빈 멍청이들과는 노는 물이 전혀 달라 Ye you know\r\n"
				+ ""));
		list.add(new Music("임영웅","사랑해 진짜", "https://cdnimg.melon.co.kr/cm2/album/images/109/23/444/10923444_20220502140600_500.jpg/melon/resize/120/quality/80/optimize", "숱한 날들 모두 내게 남아있는 추억들\r\n"
				+ "빛바랜 기억들 사이\r\n"
				+ "그대 모습만이 아련하게 빛나네\r\n"
				+ "지나간 세월이 야속하진 않아\r\n"
				+ "그댈 만났으므로\r\n"
				+ "피어날 내일을 기대해 오\r\n"
				+ "그대 내게 와줬으니\r\n"
				+ "나 진짜 진짜 당신만을 사랑하고 사랑해\r\n"
				+ "내 삶의 반쪽 그대만을\r\n"
				+ "아 나는 그대만 보고 있어\r\n"
				+ "아 나는 그대를 사랑합니다\r\n"
				+ "오색빛의 색이 물든 미완성의 그림 하나\r\n"
				+ "그래 내 마음 같겠지\r\n"
				+ "어느 날 그대가 내게 오기 전까지\r\n"
				+ "지나간 시간이 야속하진 않아\r\n"
				+ "그댈 만났으므로\r\n"
				+ "피어날 내일을 기대해\r\n"
				+ "그대 내게 와줬으니\r\n"
				+ "나 진짜 진짜 당신만을 사랑하고 사랑해\r\n"
				+ "내 삶의 반쪽 그대만을\r\n"
				+ "아 나는 그대만 보고 있어\r\n"
				+ "아 나는 그대를 사랑합니다"));
		list.add(new Music("MSG워너비(M.O.M)","듣고 싶을까", "https://cdnimg.melon.co.kr/cm2/album/images/108/80/544/10880544_20220225141002_500.jpg/melon/resize/120/quality/80/optimize", "우리 함께 듣던 그 노랠 듣고 싶을까\r\n"
				+ "듣고 나서 잠시 날 생각은 할까\r\n"
				+ "아주 혹시라도 넌 내가 보고 싶을까\r\n"
				+ "난 왜 니 목소리가 듣고 싶을까\r\n"
				+ "뻔하디 뻔한 노랫말 여서 미안해\r\n"
				+ "미안해도 부디 넌 꼭 들어줬음 해\r\n"
				+ "후회도 미련도 없는 척 떠났지만\r\n"
				+ "이게 내 진심인 걸 꼭 알아줬음 해\r\n"
				+ "우리 함께 듣던 그 노랠 듣고 싶을까\r\n"
				+ "듣고 나서 잠시 날 생각은 할까\r\n"
				+ "아주 혹시라도 넌 내가 보고 싶을까\r\n"
				+ "못난 내 목소리가 듣고 싶을까\r\n"
				+ "말없이 다 전해지는 건 없지 난 말해 지금\r\n"
				+ "몇 년째 나의 favorite one\r\n"
				+ "You the only one yeah\r\n"
				+ "Yes I know 무엇도 달라질 건 없지만\r\n"
				+ "이게 내 진심인 걸 꼭 알아줬음 해\r\n"
				+ "우리 함께 듣던 그 노랠 듣고 싶을까\r\n"
				+ "듣고 나서 잠시 날 생각은 할까\r\n"
				+ "아주 혹시라도 넌 내가 보고 싶을까\r\n"
				+ "난 왜 니 목소리가 듣고 싶을까"));
		list.add(new Music("임영웅","연애편지", "https://cdnimg.melon.co.kr/cm2/album/images/109/23/444/10923444_20220502140600_500.jpg/melon/resize/120/quality/80/optimize", "노을에 물든 저녁 하늘이\r\n"
				+ "오랜만에 참 좋은 저녁입니다\r\n"
				+ "문득 떠오른 그대 생각에\r\n"
				+ "나지막이 이름을 불러봅니다\r\n"
				+ "나도 몰래 꺼내 본 낡은 수첩엔\r\n"
				+ "그대가 너무도 많아\r\n"
				+ "차마 그립단 말 대신\r\n"
				+ "꽃잎을 넣어 보내며\r\n"
				+ "하얀 종이에 하지 못한 말\r\n"
				+ "아직 그댄 내 고운 사랑입니다\r\n"
				+ "외로이 스쳐 창을 흔드는\r\n"
				+ "바람 소리 쓸쓸한 시간입니다\r\n"
				+ "어둠 만들고 초를 태우며\r\n"
				+ "나지막이 그대를 불러봅니다\r\n"
				+ "나도 몰래 꺼내 본 낡은 사진엔\r\n"
				+ "그대가 너무도 많아\r\n"
				+ "차마 그립단 말 대신\r\n"
				+ "바라본 밤하늘에는\r\n"
				+ "아스라이 먼 작은 별 하나\r\n"
				+ "외로이 홀로 남아 깜박입니다"));
		list.add(new Music("주호", "내가 아니라도", "https://cdnimg.melon.co.kr/cm2/album/images/108/97/407/10897407_20220323150744_500.jpg/melon/resize/120/quality/80/optimize", "사랑이었다 별거 없던 내 하루에\r\n"
				+ "빛이 돼준 단한 사람\r\n"
				+ "나보다 나를 더 아껴 주던 너를\r\n"
				+ "그땐 왜 몰랐을까\r\n"
				+ "행복이었다 다시는 없을 것 같던\r\n"
				+ "잠시나마 행복했었다\r\n"
				+ "다른 사람 곁에 있는 널\r\n"
				+ "생각해 본 적 없지만\r\n"
				+ "이젠 너를 보내줘야 할 것 같아\r\n"
				+ "내가 아니라도\r\n"
				+ "눈부시게 사랑받았을 너라서\r\n"
				+ "그 소중한 시간을 나와 함께해 줘서\r\n"
				+ "고마웠어\r\n"
				+ "예쁘고 아름다웠던 너의 그날에\r\n"
				+ "함께했던 그 모든 순간이 행복했어\r\n"
				+ "내 전부였다 무엇도 바꿀 수 없던\r\n"
				+ "우리라서 행복했었다\r\n"
				+ "다른 누구라도\r\n"
				+ "나보다 더 좋은 사람 만나서\r\n"
				+ "이젠 나를 잊고 행복하게 살아\r\n"
				+ "내가 아니라도\r\n"
				+ "눈부시게 사랑받았을 너라서\r\n"
				+ "그 소중한 시간을 나와 함께해 줘서\r\n"
				+ "고마웠어"));
		list.add(new Music("The Kid LAROI, Justin Bieber", "STAY", "https://cdnimg.melon.co.kr/cm2/album/images/106/46/395/10646395_20210707141710_500.jpg/melon/resize/120/quality/80/optimize", "I do the same thing I told you\r\n"
				+ "that I never would\r\n"
				+ "I told you I'd change\r\n"
				+ "even when I knew I never could\r\n"
				+ "I know that I can't find\r\n"
				+ "nobody else\r\n"
				+ "as good as you\r\n"
				+ "I need you to stay\r\n"
				+ "need you to stay hey Oh\r\n"
				+ "I get drunk wake up\r\n"
				+ "I'm wasted still\r\n"
				+ "I realize the time\r\n"
				+ "that I wasted here\r\n"
				+ "I feel like you can't\r\n"
				+ "feel the way I feel\r\n"
				+ "Oh I'll be fucked up\r\n"
				+ "if you can't be right here\r\n"
				+ "Oh ooh-woah\r\n"
				+ "Oh ooh-woah ooh-woah\r\n"
				+ "Oh ooh-woah\r\n"
				+ "Oh ooh-woah ooh-woah\r\n"
				+ "Oh ooh-woah\r\n"
				+ "Oh ooh-woah ooh-woah\r\n"
				+ "Oh I'll be fucked up\r\n"
				+ "if you can't be right here\r\n"
				+ "I do the same thing I told you\r\n"
				+ "that I never would\r\n"
				+ "I told you I'd change\r\n"
				+ "even when I knew I never could\r\n"
				+ "I know that I can't find\r\n"
				+ "nobody else\r\n"
				+ "as good as you\r\n"
				+ "I need you to stay\r\n"
				+ "need you to stay hey\r\n"
				+ "I do the same thing I told you\r\n"
				+ "that I never would\r\n"
				+ "I told you I'd change\r\n"
				+ "even when I knew I never could\r\n"
				+ "I know that I can't find\r\n"
				+ "nobody else"));
		list.add(new Music("Charlie Puth","That's Hilarious", "https://cdnimg.melon.co.kr/cm2/album/images/108/44/485/10844485_20220407163235_500.jpg/melon/resize/120/quality/80/optimize", "Look how all tables,\r\n"
				+ "Look how all the tables have turned,\r\n"
				+ "Guess you’re finally realizing how bad you messed it up\r\n"
				+ "Girl you’re only making,\r\n"
				+ "Girl you’re only making it worse,\r\n"
				+ "When you call like you always do when you want someone\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "Pre-Chorus:\r\n"
				+ "You took away a year,\r\n"
				+ "of my fucking life and I can’t get it back no more\r\n"
				+ "So when I see those tears,\r\n"
				+ "Coming out your eyes I hope it’s me there for\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "Chorus:\r\n"
				+ "You didn’t love when you had me\r\n"
				+ "But now you need me so badly\r\n"
				+ "You can’t be serious\r\n"
				+ "That’s hilarious\r\n"
				+ "Thinking I would still want you\r\n"
				+ "After the things you put me through\r\n"
				+ "Yea You’re delirious\r\n"
				+ "That’s hilarious"));
		list.add(new Music("케이시(Kassy)","늦은 밤 헤어지긴 너무 아쉬워", "https://cdnimg.melon.co.kr/cm2/album/images/109/60/568/10960568_20220518153132_500.jpg/melon/resize/120/quality/80/optimize", "어쩌면 너도 나와 같은 꿈 꿀까\r\n"
				+ "매일 마주 보며 눈뜨는 하루\r\n"
				+ "늦은 밤 헤어지긴 너무 아쉬워\r\n"
				+ "널 많이 사랑하나 봐\r\n"
				+ "유난히 날씨가 좋은 날\r\n"
				+ "넌 나를 설레이게 해\r\n"
				+ "영화 속에서만 보던 일들이\r\n"
				+ "요즘 내 일상인 듯해\r\n"
				+ "어쩌면 너도 나와 같은 꿈 꿀까\r\n"
				+ "매일 마주 보며 눈뜨는 하루\r\n"
				+ "늦은 밤 헤어지긴 너무 아쉬워\r\n"
				+ "널 많이 사랑하나 봐\r\n"
				+ "오늘 너에게 고백하겠어\r\n"
				+ "취해서 하는 말이 아냐\r\n"
				+ "참아온 진심인 거야\r\n"
				+ "하루 종일 아무것도 안 해도\r\n"
				+ "너랑 있는 게 젤 좋아\r\n"
				+ "달빛도 하늘 아래 우리를 비추고\r\n"
				+ "온 세상이 모두 잠든 것 같아\r\n"
				+ "늦은 밤 헤어지긴 너무 아쉬워\r\n"
				+ "널 많이 사랑하나 봐\r\n"
				+ "네가 살아가는 순간에\r\n"
				+ "그 모든 순간에 내가 있음 해\r\n"
				+ "고마워 내 인생에 나타나줘서\r\n"
				+ "이렇게 날 안아줘서\r\n"
				+ "오늘 너에게 고백하겠어"));
		list.add(new Music("임영웅","보금자리", "https://cdnimg.melon.co.kr/cm2/album/images/109/23/444/10923444_20220502140600_500.jpg/melon/resize/120/quality/80/optimize", "그대 사랑이 나였음 좋겠다\r\n"
				+ "아무것도 필요 없어요\r\n"
				+ "든든한 품에 안겨 잠들고 싶어라\r\n"
				+ "내 사랑의 보금자리\r\n"
				+ "아무것도 바라지 않아요\r\n"
				+ "당신만 있으면 돼\r\n"
				+ "한 눈 팔지 않고 사랑할래요\r\n"
				+ "돈도 필요 없어 백도 필요 없어\r\n"
				+ "당신만 있으면 돼\r\n"
				+ "그대 사랑이 나였음 좋겠다\r\n"
				+ "아무것도 필요 없어요\r\n"
				+ "든든한 품에 안겨 잠들고 싶어라\r\n"
				+ "내 사랑의 보금자리\r\n"
				+ "아무것도 바라지 않아요\r\n"
				+ "당신만 있으면 돼\r\n"
				+ "한 눈 팔지 않고 사랑할래요\r\n"
				+ "돈도 필요 없어 백도 필요 없어\r\n"
				+ "당신만 있으면 돼\r\n"
				+ "아무것도 바라지 않아요\r\n"
				+ "당신만 있으면 돼\r\n"
				+ "한 눈 팔지 않고 사랑할래요\r\n"
				+ "돈도 필요 없어 백도 필요 없어\r\n"
				+ "당신만 있으면 돼\r\n"
				+ "당신만 있으면 돼"));
		list.add(new Music("임영웅","사랑해요 그대를", "https://cdnimg.melon.co.kr/cm2/album/images/109/23/444/10923444_20220502140600_500.jpg/melon/resize/120/quality/80/optimize", "너무나 고마운 사람\r\n"
				+ "너무나 따뜻한 사람\r\n"
				+ "한 번도 잊어본 적 없는\r\n"
				+ "내 마음속에 그 사람\r\n"
				+ "나 그대 생각만 해도\r\n"
				+ "가슴이 뭉클해지고\r\n"
				+ "그런 당신 내 곁에 있어\r\n"
				+ "나는 행복한 사람\r\n"
				+ "그대는 나만의 사랑\r\n"
				+ "그대는 나만의 행복\r\n"
				+ "세월 가도 영원히\r\n"
				+ "당신은 나만의 사랑\r\n"
				+ "사랑해요 그대를\r\n"
				+ "사랑해요 그대를\r\n"
				+ "이 생명 다할 때까지\r\n"
				+ "당신은 내 사랑\r\n"
				+ "사랑해요 그대를\r\n"
				+ "사랑해요 그대를\r\n"
				+ "이 생명 다할 때까지\r\n"
				+ "당신은 내사랑\r\n"
				+ "그대는 나만의 사랑\r\n"
				+ "그대는 나만의 행복\r\n"
				+ "세월 가도 영원히\r\n"
				+ "당신은 나만의 사랑"));
		list.add(new Music("세븐틴","Dar+ing", "https://cdnimg.melon.co.kr/cm2/album/images/109/22/231/10922231_20220527120653_500.jpg/melon/resize/120/quality/80/optimize", "You know without you I’m so lonely\r\n"
				+ "When you’re not here 911 calling\r\n"
				+ "Into your heat again I’m diving\r\n"
				+ "Darling you Darling you baby\r\n"
				+ "\r\n"
				+ "Fighting round in circles where is the way out\r\n"
				+ "‘Cause I know that our love was hotter than the sun\r\n"
				+ "Yeah the taste of this tequila I’m drinking now\r\n"
				+ "Isn’t bitter than my heart\r\n"
				+ "\r\n"
				+ "(If you know this)\r\n"
				+ "I want to know our problem blood type or DNA\r\n"
				+ "Friends see my feed and worry, do you babe? Yeah\r\n"
				+ "Been waiting for your call every night\r\n"
				+ "But I can’t wait no more\r\n"
				+ "Dialing you-u-u, sorry darling you\r\n"
				+ "\r\n"
				+ "You know without you I’m so lonely\r\n"
				+ "When you’re not here 911 calling\r\n"
				+ "Into your heat again I’m diving\r\n"
				+ "Darling you Darling you baby\r\n"
				+ "\r\n"
				+ "You know without you I’m so lonely\r\n"
				+ "If you won’t be here 911 calling\r\n"
				+ "Falling to you I’m always diving\r\n"
				+ "Darling you Darling you baby\r\n"
				+ "\r\n"
				+ "Darling with me under the sun\r\n"
				+ "I know that you’re my one"));
		list.add(new Music("방탄소년단","Dynamite", "https://cdnimg.melon.co.kr/cm2/album/images/104/79/150/10479150_20200918102847_500.jpg/melon/resize/120/quality/80/optimize", "Cos ah ah\r\n"
				+ "I’m in the stars tonight\r\n"
				+ "So watch me bring the fire\r\n"
				+ "and set the night alight\r\n"
				+ "Shoes on get up in the morn\r\n"
				+ "Cup of milk let’s rock and roll\r\n"
				+ "King Kong kick the drum\r\n"
				+ "rolling on like a rolling stone\r\n"
				+ "Sing song when I’m walking home\r\n"
				+ "Jump up to the top LeBron\r\n"
				+ "Ding dong call me on my phone\r\n"
				+ "Ice tea and a game of ping pong\r\n"
				+ "This is getting heavy\r\n"
				+ "Can you hear the bass boom\r\n"
				+ "I’m ready\r\n"
				+ "Life is sweet as honey\r\n"
				+ "Yeah this beat cha ching\r\n"
				+ "like money\r\n"
				+ "Disco overload I’m into\r\n"
				+ "that I’m good to go\r\n"
				+ "I'm diamond you know I glow up\r\n"
				+ "Hey so let’s go\r\n"
				+ "Cos ah ah\r\n"
				+ "I’m in the stars tonight\r\n"
				+ "So watch me bring the fire\r\n"
				+ "and set the night alight\r\n"
				+ "Shining through the city\r\n"
				+ "with a little funk and soul\r\n"
				+ "So I’mma light it up\r\n"
				+ "like dynamite woah\r\n"
				+ "Bring a friend join the crowd\r\n"
				+ "Whoever wanna come along\r\n"
				+ "Word up talk the talk\r\n"
				+ "just move like we off the wall\r\n"
				+ "Day or night the sky’s alight\r\n"
				+ "So we dance to the break of dawn\r\n"
				+ "Ladies and gentlemen\r\n"
				+ "I got the medicine\r\n"
				+ "so you should keep ya\r\n"
				+ "eyes on the ball huh\r\n"
				+ "This is getting heavy\r\n"
				+ "Can you hear the bass boom"));
		list.add(new Music("태연 (TAEYEON)","Weekend", "https://cdnimg.melon.co.kr/cm2/album/images/106/45/654/10645654_20210706155154_500.jpg/melon/resize/120/quality/80/optimize", "가장 가까운 바다\r\n"
				+ "혼자만의 영화관\r\n"
				+ "그냥 이끌리는 대로 해도 괜찮으니까\r\n"
				+ "Every morning 울린\r\n"
				+ "Beep beep beep beep 소리\r\n"
				+ "귀에 윙윙윙 맴도는\r\n"
				+ "나를 재촉하던 모닝콜 없이 일어나\r\n"
				+ "Cheese cake 한 입\r\n"
				+ "유리컵 한가득\r\n"
				+ "내린 커피 한 잔\r\n"
				+ "아이스로 할래 아주 여유롭게\r\n"
				+ "문득 시곌 보니\r\n"
				+ "벌써 시간은 열두시\r\n"
				+ "그래도 아주 느긋해\r\n"
				+ "그리곤 하품 한 번\r\n"
				+ "한껏 기지개도 켜고\r\n"
				+ "생각해 오늘 뭐 할까\r\n"
				+ "창문 너머 계절에 시선이 닿은 그 순간\r\n"
				+ "쏟아지는 햇살 내 맘을 두드려\r\n"
				+ "내게 손짓하는 싱그러운 바람 타고서\r\n"
				+ "떠나볼래 When the weekend comes\r\n"
				+ "I can do whatever I want\r\n"
				+ "바람 따라 흩어진 cloud\r\n"
				+ "더 자유롭게 we can go\r\n"
				+ "가장 가까운 바다\r\n"
				+ "혼자만의 영화관\r\n"
				+ "그냥 이끌리는 대로 해도 괜찮으니까\r\n"
				+ "훌쩍 떠나보는 drive\r\n"
				+ "뚜벅 걸어도 좋아"));
		list.add(new Music("aespa","Next Level", "https://cdnimg.melon.co.kr/cm2/album/images/106/09/232/10609232_20210517155130_500.jpg/melon/resize/120/quality/80/optimize", "I’m on the Next Level Yeah\r\n"
				+ "절대적 룰을 지켜\r\n"
				+ "내 손을 놓지 말아\r\n"
				+ "결속은 나의 무기\r\n"
				+ "광야로 걸어가\r\n"
				+ "알아 네 Home ground\r\n"
				+ "위협에 맞서서\r\n"
				+ "제껴라 제껴라 제껴라\r\n"
				+ "\r\n"
				+ "상상도 못한 Black out\r\n"
				+ "유혹은 깊고 진해\r\n"
				+ "(Too hot too hot)\r\n"
				+ "맞잡은 손을 놓쳐\r\n"
				+ "난 절대 포기 못해\r\n"
				+ "\r\n"
				+ "I’m on the Next Level\r\n"
				+ "저 너머의 문을 열어\r\n"
				+ "Next Level\r\n"
				+ "널 결국엔 내가 부셔\r\n"
				+ "Next Level\r\n"
				+ "KOSMO에 닿을 때까지\r\n"
				+ "Next Level\r\n"
				+ "제껴라 제껴라 제껴라\r\n"
				+ "\r\n"
				+ "La la la la la la\r\n"
				+ "La la la la la la\r\n"
				+ "La la la la la la\r\n"
				+ "La la la la la"));
		list.add(new Music("방탄소년단","Butter", "https://cdnimg.melon.co.kr/cm2/album/images/106/12/483/10612483_20210521111412_500.jpg/melon/resize/120/quality/80/optimize", "Smooth like butter\r\n"
				+ "Like a criminal undercover\r\n"
				+ "Gon’ pop like trouble\r\n"
				+ "Breakin’ into your heart like that\r\n"
				+ "\r\n"
				+ "Cool shade stunner\r\n"
				+ "Yeah I owe it all to my mother\r\n"
				+ "Hot like summer\r\n"
				+ "Yeah I’m makin’ you sweat like that\r\n"
				+ "\r\n"
				+ "Break it down\r\n"
				+ "\r\n"
				+ "Oh when I look in the mirror\r\n"
				+ "I’ll melt your heart into 2\r\n"
				+ "I got that superstar glow so\r\n"
				+ "Do the boogie like\r\n"
				+ "\r\n"
				+ "Side step right left to my beat (heartbeat)\r\n"
				+ "High like the moon rock with me baby\r\n"
				+ "Know that I got that heat\r\n"
				+ "Let me show you ‘cause talk is cheap\r\n"
				+ "Side step right left to my beat (heartbeat)\r\n"
				+ "Get it, let it roll\r\n"
				+ "\r\n"
				+ "Smooth like butter\r\n"
				+ "Pull you in like no other\r\n"
				+ "Don’t need no Usher\r\n"
				+ "To remind me you got it bad\r\n"
				+ "\r\n"
				+ "Ain’t no other\r\n"
				+ "That can sweep you up like a robber\r\n"
				+ "Straight up, I got ya\r\n"
				+ "Makin’ you fall like that\r\n"
				+ "\r\n"
				+ "Break it down\r\n"
				+ ""));
		list.add(new Music("주시크 (Joosiq)","너를 생각해", "https://cdnimg.melon.co.kr/cm2/album/images/107/16/399/10716399_20210916173429_500.jpg/melon/resize/120/quality/80/optimize", "너를 들려주고 싶었어\r\n"
				+ "이 노랠 만들 때\r\n"
				+ "아마 니가 정말 많이 좋아할꺼야\r\n"
				+ "이젠 내겐 니가 없어서\r\n"
				+ "나 혼자 불러도\r\n"
				+ "혹시 듣게 되면 그게 니 얘기라고\r\n"
				+ "난 노랠 만들 땐\r\n"
				+ "늘 너를 생각해\r\n"
				+ "어딘가 혼자 진지한 표정\r\n"
				+ "고개를 끄덕거리고 나선\r\n"
				+ "항상 흥얼거리며 따라 불렀어\r\n"
				+ "나를 보며 신나있던 너에게\r\n"
				+ "불러주고 싶던 노래를\r\n"
				+ "왜 이제야 겨우 완성했을까\r\n"
				+ "이 노랜 널 사랑한다는 내 얘기가\r\n"
				+ "잔뜩 들어갔어야 하는 노랜데\r\n"
				+ "너를 들려주고 싶었어\r\n"
				+ "이 노랠 만들 때\r\n"
				+ "아마 니가 정말 많이 좋아할꺼야\r\n"
				+ "이젠 내겐 니가 없어서\r\n"
				+ "나 혼자 불러도\r\n"
				+ "혹시 듣게 되면 그게 니 얘기라고\r\n"
				+ "니가 자주 가곤했던 카페에\r\n"
				+ "이 노래가 나올 때까지\r\n"
				+ "니 친구가 따라 부를 때까지\r\n"
				+ "이 노랠 유명해지게 계속 불러서\r\n"
				+ "나는 너에게로 꼭 닿고 말거야\r\n"
				+ "너를 들려주고 싶었어"));
		list.add(new Music("YENA (최예나)","SMILEY (Feat. BIBI)", "https://cdnimg.melon.co.kr/cm2/album/images/108/42/611/10842611_20220117110002_500.jpg/melon/resize/120/quality/80/optimize", "울지 마 울지 마\r\n"
				+ "어린아이같이\r\n"
				+ "웃는 게 웃는 게\r\n"
				+ "이기는 거라고\r\n"
				+ "You are so cute\r\n"
				+ "You are so dumb\r\n"
				+ "네가 하는 말이\r\n"
				+ "오늘따라 듣기 싫어\r\n"
				+ "하늘을 한 번 쳐다보고\r\n"
				+ "내가 꾹 참고\r\n"
				+ "맘을 다 잡고\r\n"
				+ "네게 밝게 웃어줄게\r\n"
				+ "And I say Hey\r\n"
				+ "I’m gonna make it\r\n"
				+ "Smile Smile Smile away\r\n"
				+ "예쁘게 웃고 넘겨버릴래\r\n"
				+ "Just Smile away\r\n"
				+ "Just Smile away\r\n"
				+ "아픔 슬픔 외로움 잊게\r\n"
				+ "I say hey\r\n"
				+ "I never wanna Cry Cry Cry all day\r\n"
				+ "갑자기 눈물이 차오를 땐\r\n"
				+ "Just Smile away\r\n"
				+ "Just Smile away\r\n"
				+ "안녕이라 말할래\r\n"
				+ "With my Smiley face\r\n"
				+ "비웃을 때 빼고\r\n"
				+ "내 입꼬리는 Chillin’\r\n"
				+ "나빠야지 살아남지 넌 뭐해\r\n"
				+ "귀엽고 예쁘면 장땡이냐 근데\r\n"
				+ "널 보고 있으니까 기분이가 좋네"));
		list.add(new Music("케이시 (Kassy)","언제나 사랑해", "https://cdnimg.melon.co.kr/cm2/album/images/108/57/681/10857681_20220204162442_500.jpg/melon/resize/120/quality/80/optimize", "둘이 손잡고 걸을 때\r\n"
				+ "마주 보며 또 웃을 때\r\n"
				+ "사랑한다 말하지 않아도 알아\r\n"
				+ "널 만나러 가는 길에\r\n"
				+ "내 입가에 늘 환한 미소만이\r\n"
				+ "흐르고 있어\r\n"
				+ "사랑해 너를 사랑해\r\n"
				+ "눈물 나도록 사랑해\r\n"
				+ "저기 밤하늘의 별보다\r\n"
				+ "보석보다 네가 더 소중해\r\n"
				+ "얼마나 내가 얼마나 너를 사랑하는지\r\n"
				+ "내 모든 걸 너에게 줄게\r\n"
				+ "속상하고 힘이 들 때\r\n"
				+ "열이 나고 아파할 때\r\n"
				+ "옆에서 늘 힘이 돼준 사람 너야\r\n"
				+ "집에 돌아오는 길에\r\n"
				+ "내 귓가엔 늘 너의 음성만이\r\n"
				+ "흐르고 있어\r\n"
				+ "사랑해 너를 사랑해\r\n"
				+ "눈물 나도록 사랑해\r\n"
				+ "저기 밤하늘의 별보다\r\n"
				+ "보석보다 네가 더 소중해\r\n"
				+ "얼마나 내가 얼마나 너를 사랑하는지\r\n"
				+ "내 모든 걸 너에게 줄게\r\n"
				+ "세월 지나 많이 변했을 때\r\n"
				+ "미운 나의 손을 잡아줄 사람\r\n"
				+ "먼 훗날 아주 먼 훗날\r\n"
				+ "우리 눈 감는 그날에\r\n"
				+ "나를 사랑해 준 너에게 고맙다고"));
		list.add(new Music("성시경","너의 모든 순간", "https://cdnimg.melon.co.kr/cm/album/images/022/32/505/2232505_500.jpg/melon/resize/120/quality/80/optimize", "이윽고 내가 한눈에\r\n"
				+ "너를 알아봤을 때\r\n"
				+ "모든 건 분명 달라지고 있었어\r\n"
				+ "내 세상은 널 알기 전과 후로 나뉘어\r\n"
				+ "니가 숨 쉬면 따스한 바람이 불어와\r\n"
				+ "니가 웃으면 눈부신 햇살이 비춰\r\n"
				+ "거기 있어줘서 그게 너라서\r\n"
				+ "가끔 내 어깨에 가만히 기대주어서\r\n"
				+ "나는 있잖아 정말 빈틈없이 행복해\r\n"
				+ "너를 따라서 시간은 흐르고 멈춰\r\n"
				+ "물끄러미 너를 들여다 보곤 해\r\n"
				+ "그것 말고는 아무것도 할 수 없어서\r\n"
				+ "너의 모든 순간 그게\r\n"
				+ "나였으면 좋겠다\r\n"
				+ "생각만 해도 가슴이 차올라\r\n"
				+ "나는 온통 너로\r\n"
				+ "보고 있으면 왠지 꿈처럼 아득한 것\r\n"
				+ "몇 광년 동안 날 향해 날아온 별빛\r\n"
				+ "또 지금의 너\r\n"
				+ "거기 있어줘서 그게 너라서"));
		list.add(new Music("주시크 (Joosiq)","아무래도 난", "https://cdnimg.melon.co.kr/cm2/album/images/109/03/658/10903658_20220329185034_500.jpg/melon/resize/120/quality/80/optimize", "아무렇지 않게 내 하루가 또\r\n"
				+ "지나갈 쯤에 문득\r\n"
				+ "네가 없다는 게 익숙해진 내가\r\n"
				+ "낯설어지곤 해 yeah\r\n"
				+ "이제와 너 없는 난 의미 없다고\r\n"
				+ "되돌릴 수 없는 우리겠지만\r\n"
				+ "네가 좋아했던 그 노랠 우연히\r\n"
				+ "듣게 됐어 아무래도 난\r\n"
				+ "Baby I Need You\r\n"
				+ "좀 늦었겠지만\r\n"
				+ "다시 하고 싶어\r\n"
				+ "여전히 I Need you\r\n"
				+ "Need You\r\n"
				+ "좀 어렵겠지만\r\n"
				+ "너 없인 안돼 난\r\n"
				+ "너도 알잖아\r\n"
				+ "Baby I need you now\r\n"
				+ "Baby I need you now\r\n"
				+ "Baby I need you now\r\n"
				+ "몇 곡의 노래로 너를 불렀을까\r\n"
				+ "너도 들었겠지만\r\n"
				+ "아직도 궁금해\r\n"
				+ "내가 없이 보낸\r\n"
				+ "너의 지금은 어때\r\n"
				+ "이제와 너 없는 난 의미 없다고\r\n"
				+ "되돌릴 수 없는 우리겠지만\r\n"
				+ "네가 좋아했던 그 노랠 우연히\r\n"
				+ "불러 봤어 아무래도 난\r\n"
				+ "Baby I Need You\r\n"
				+ "좀 늦었겠지만\r\n"
				+ "다시 하고 싶어"));
		list.add(new Music("아이유","드라마", "https://cdnimg.melon.co.kr/cm2/album/images/108/27/816/10827816_20211229143632_500.jpg/melon/resize/120/quality/80/optimize", "나도 한때는 그이의 손을 잡고\r\n"
				+ "내가 온 세상 주인공이 된 듯\r\n"
				+ "꽃송이의 꽃잎 하나하나까지\r\n"
				+ "모두 날 위해 피어났지\r\n"
				+ "\r\n"
				+ "올림픽대로 뚝섬 유원지\r\n"
				+ "서촌 골목골목 예쁜 식당\r\n"
				+ "나를 휘청거리게 만든\r\n"
				+ "주옥같은 대사들\r\n"
				+ "\r\n"
				+ "다시 누군가 사랑할 수 있을까\r\n"
				+ "예쁘다는 말 들을 수 있을까\r\n"
				+ "하루 단 하루만 기회가 온다면\r\n"
				+ "죽을힘을 다해 빛나리\r\n"
				+ "\r\n"
				+ "언제부턴가 급격하게\r\n"
				+ "단조로 바뀌던 배경음악\r\n"
				+ "조명이 꺼진 세트장에\r\n"
				+ "혼자 남겨진 나는"));
		
		
		return list;
	}
}
